/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:bb2c5d2a74b7519a0ac4b37ee5fa1ef5:8cdfd3433d4cd415846bd6f0dce90459:d4b3315b352c3a8feefa01b3540b236b$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Particles SpriteSheet
	{
		public const string Particles_LeafT1 = "Particles/LeafT1";
		public const string Particles_LeafT2 = "Particles/LeafT2";
		public const string Particles_LeafT3 = "Particles/LeafT3";
		public const string Particles_LeafT4 = "Particles/LeafT4";
		public const string Particles_LeafT5 = "Particles/LeafT5";
		public const string Particles_LeafT6 = "Particles/LeafT6";
		public const string Particles_LeafT7 = "Particles/LeafT7";
		public const string Particles_LeafT8 = "Particles/LeafT8";
		public const string Particles_LeafT9 = "Particles/LeafT9";
		public const string Particles_LeafT10 = "Particles/LeafT10";
		public const string Particles_LeafT11 = "Particles/LeafT11";
		public const string Particles_LeafT12 = "Particles/LeafT12";
		public const string Particles_LeafT13 = "Particles/LeafT13";
		public const string Particles_LeafT14 = "Particles/LeafT14";
		public const string Particles_LeafT15 = "Particles/LeafT15";
		public const string Particles_LeafT16 = "Particles/LeafT16";
		public const string Particles_LeafT17 = "Particles/LeafT17";
		public const string Particles_LeafT18 = "Particles/LeafT18";
		public const string Particles_LeafT19 = "Particles/LeafT19";
		public const string Particles_LeafT20 = "Particles/LeafT20";
		public const string Particles_LeafT21 = "Particles/LeafT21";
		public const string Particles_LeafT22 = "Particles/LeafT22";
		public const string Particles_LeafT23 = "Particles/LeafT23";
		public const string Particles_LeafT24 = "Particles/LeafT24";
		public const string Particles_LeafT25 = "Particles/LeafT25";
		public const string Particles_LeafT26 = "Particles/LeafT26";
		public const string Particles_LeafT27 = "Particles/LeafT27";
		public const string Particles_LeafT28 = "Particles/LeafT28";
		public const string Particles_LeafT29 = "Particles/LeafT29";
		public const string Particles_LeafT30 = "Particles/LeafT30";
		public const string Particles_LeafT31 = "Particles/LeafT31";
		public const string Particles_LeafT32 = "Particles/LeafT32";
		public const string Particles_LeafT33 = "Particles/LeafT33";
		public const string Particles_LeafT34 = "Particles/LeafT34";
		public const string Particles_LeafT35 = "Particles/LeafT35";
		public const string Particles_LeafT36 = "Particles/LeafT36";
		public const string Particles_LeafT37 = "Particles/LeafT37";
		public const string Particles_LeafT38 = "Particles/LeafT38";
		public const string Particles_LeafT39 = "Particles/LeafT39";
		public const string Particles_LeafT40 = "Particles/LeafT40";
		public const string Particles_LeafT41 = "Particles/LeafT41";
		public const string Particles_LeafT42 = "Particles/LeafT42";
		public const string Particles_LeafT43 = "Particles/LeafT43";
		public const string Particles_LeafT44 = "Particles/LeafT44";
		public const string Particles_LeafT45 = "Particles/LeafT45";
		public const string Particles_LeafT46 = "Particles/LeafT46";
	}
}