/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:ac69abb325739cb243e74fa78d7486f6:145cf396cbcb8ccfecd716a797dc7156:bdf563343612dbc62b35eb797339160d$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Corporation SpriteSheet
	{
		public const string Corporation_Floor_00 = "Corporation/Floor_00";
		public const string Corporation_Floor_01 = "Corporation/Floor_01";
		public const string Corporation_Floor_02 = "Corporation/Floor_02";
		public const string Corporation_Floor_03 = "Corporation/Floor_03";
		public const string Corporation_Floor_04 = "Corporation/Floor_04";
		public const string Corporation_Floor_05 = "Corporation/Floor_05";
		public const string Corporation_Floor_06 = "Corporation/Floor_06";
		public const string Corporation_Floor_07 = "Corporation/Floor_07";
		public const string Corporation_Floor_08 = "Corporation/Floor_08";
		public const string Corporation_Floor_09 = "Corporation/Floor_09";
		public const string Corporation_Glass_Wall_00 = "Corporation/Glass Wall_00";
		public const string Corporation_Glass_Wall_01 = "Corporation/Glass Wall_01";
		public const string Corporation_Glass_Wall_02 = "Corporation/Glass Wall_02";
		public const string Corporation_Glass_Wall_03 = "Corporation/Glass Wall_03";
		public const string Corporation_Wall_00 = "Corporation/Wall_00";
		public const string Corporation_Wall_01 = "Corporation/Wall_01";
		public const string Corporation_Wall_02 = "Corporation/Wall_02";
		public const string Corporation_Wall_03 = "Corporation/Wall_03";
		public const string Corporation_Wall_04 = "Corporation/Wall_04";
		public const string Corporation_Wall_05 = "Corporation/Wall_05";
	}
}