/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:b1989e04eb2c91cf2b5a0f909ad0838e:b9f3f62531a42b6accaec59e7888a0b1:bdf563343612dbc62b35eb797339160d$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Corporation SpriteSheet
	{
		public const string Corporation_Air_Vent1 = "Corporation/Air Vent1";
		public const string Corporation_Air_Vent2 = "Corporation/Air Vent2";
		public const string Corporation_Air_Vent3 = "Corporation/Air Vent3";
		public const string Corporation_Chair_Egg1 = "Corporation/Chair_Egg1";
		public const string Corporation_Chair_Egg2 = "Corporation/Chair_Egg2";
		public const string Corporation_Desk1 = "Corporation/Desk1";
		public const string Corporation_Desk2 = "Corporation/Desk2";
		public const string Corporation_Door_Glass = "Corporation/Door_Glass";
		public const string Corporation_Door_Single1 = "Corporation/Door_Single1";
		public const string Corporation_Door_Single2 = "Corporation/Door_Single2";
		public const string Corporation_Door_Single3 = "Corporation/Door_Single3";
		public const string Corporation_Door_Single4 = "Corporation/Door_Single4";
		public const string Corporation_Door_Single5 = "Corporation/Door_Single5";
		public const string Corporation_Door_Single6 = "Corporation/Door_Single6";
		public const string Corporation_Door_Single7 = "Corporation/Door_Single7";
		public const string Corporation_Door_Single8 = "Corporation/Door_Single8";
		public const string Corporation_Door_SingleT2 = "Corporation/Door_SingleT2";
		public const string Corporation_Door_SingleT3 = "Corporation/Door_SingleT3";
		public const string Corporation_Door_SingleT4 = "Corporation/Door_SingleT4";
		public const string Corporation_Door_SingleT5 = "Corporation/Door_SingleT5";
		public const string Corporation_Door_SingleT6 = "Corporation/Door_SingleT6";
		public const string Corporation_Door_SingleT7 = "Corporation/Door_SingleT7";
		public const string Corporation_Door_SingleT8 = "Corporation/Door_SingleT8";
		public const string Corporation_Door_SingleT9 = "Corporation/Door_SingleT9";
		public const string Corporation_Floor_00 = "Corporation/Floor_00";
		public const string Corporation_Floor_01 = "Corporation/Floor_01";
		public const string Corporation_Floor_02 = "Corporation/Floor_02";
		public const string Corporation_Floor_03 = "Corporation/Floor_03";
		public const string Corporation_Floor_04 = "Corporation/Floor_04";
		public const string Corporation_Floor_05 = "Corporation/Floor_05";
		public const string Corporation_Floor_06 = "Corporation/Floor_06";
		public const string Corporation_Floor_07 = "Corporation/Floor_07";
		public const string Corporation_Floor_08 = "Corporation/Floor_08";
		public const string Corporation_Floor_09 = "Corporation/Floor_09";
		public const string Corporation_Glass_Wall_0 = "Corporation/Glass Wall_0";
		public const string Corporation_Glass_Wall_1 = "Corporation/Glass Wall_1";
		public const string Corporation_Glass_Wall_2 = "Corporation/Glass Wall_2";
		public const string Corporation_Glass_Wall_3 = "Corporation/Glass Wall_3";
		public const string Corporation_Pillow = "Corporation/Pillow";
		public const string Corporation_Sofa = "Corporation/Sofa";
		public const string Corporation_SurveilanceCamera1 = "Corporation/SurveilanceCamera1";
		public const string Corporation_SurveilanceCamera2 = "Corporation/SurveilanceCamera2";
		public const string Corporation_Terminal_Wall1 = "Corporation/Terminal_Wall1";
		public const string Corporation_Terminal_Wall2 = "Corporation/Terminal_Wall2";
		public const string Corporation_Terminal_Wall3 = "Corporation/Terminal_Wall3";
		public const string Corporation_Terminal_Wall4 = "Corporation/Terminal_Wall4";
		public const string Corporation_TV_Wall1 = "Corporation/TV_Wall1";
		public const string Corporation_TV_Wall2 = "Corporation/TV_Wall2";
		public const string Corporation_TV_Wall3 = "Corporation/TV_Wall3";
		public const string Corporation_VendingMachine = "Corporation/VendingMachine";
		public const string Corporation_Wall_00 = "Corporation/Wall_00";
		public const string Corporation_Wall_01 = "Corporation/Wall_01";
		public const string Corporation_Wall_02 = "Corporation/Wall_02";
		public const string Corporation_Wall_03 = "Corporation/Wall_03";
		public const string Corporation_Wall_04 = "Corporation/Wall_04";
		public const string Corporation_Wall_05 = "Corporation/Wall_05";
		public const string Corporation_Window1 = "Corporation/Window1";
		public const string Corporation_Window2 = "Corporation/Window2";
	}
}